
'use server';

/**
 * @fileOverview This file defines a Genkit flow for AI-powered image generation for travel packages.
 *
 * It generates a new, appealing image based on the package title and a descriptive prompt.
 *
 * @module src/ai/flows/ai-image-selection
 *
 * @interface AiImageSelectionInput - The input type for the aiImageSelection function.
 * @interface AiImageSelectionOutput - The output type for the aiImageSelection function.
 * @function aiImageSelection - The main function to generate an image using AI.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiImageSelectionInputSchema = z.object({
  title: z.string().describe('The title of the package for which an image is being generated.'),
  description: z.string().describe('A brief description of the travel package.'),
});
export type AiImageSelectionInput = z.infer<typeof AiImageSelectionInputSchema>;

const AiImageSelectionOutputSchema = z.object({
  generatedImageUrl: z.string().url().describe('The AI-generated image URL.'),
  reason: z.string().describe('A brief note on the generated image.'),
});
export type AiImageSelectionOutput = z.infer<typeof AiImageSelectionOutputSchema>;


const aiImageSelectionFlow = ai.defineFlow(
  {
    name: 'aiImageGenerationFlow',
    inputSchema: AiImageSelectionInputSchema,
    outputSchema: AiImageSelectionOutputSchema,
  },
  async input => {
    const { media } = await ai.generate({
        model: 'googleai/imagen-4.0-fast-generate-001',
        prompt: `Create a breathtaking, photorealistic travel photograph for a package titled "${input.title}". The scene should capture the essence of: "${input.description}". The image must be vibrant, inviting, and look like a professional photograph from a high-end travel magazine. Focus on dramatic lighting and an epic sense of scale.`,
    });
    
    const imageUrl = media?.url;
    if (!imageUrl) {
        throw new Error("Image generation failed to return a URL.");
    }
    
    return {
        generatedImageUrl: imageUrl,
        reason: 'This image was generated by AI based on the package title and description to create a unique and appealing visual.'
    };
  }
);


export async function aiImageSelection(input: AiImageSelectionInput): Promise<AiImageSelectionOutput> {
  // Check if there is any title to select from.
  if (!input.title) {
    throw new Error('No title provided for AI image generation.');
  }

  try {
    return await aiImageSelectionFlow(input);
  } catch (error) {
    console.error("AI image generation failed, using fallback.", error);
    // Fallback: return a placeholder image if the AI flow fails.
    return {
      generatedImageUrl: 'https://placehold.co/1200x800/222831/46C7C7?text=Image+Generation\\nUnavailable',
      reason: 'This is a default image. The AI image generation feature is currently unavailable.'
    };
  }
}
