
import type { Package, Review, Continent, Country } from '@/types';

export const countries: Country[] = [
    { name: 'Tanzania', flag: '🇹🇿', heroImage: 'https://picsum.photos/seed/tanzania-hero/1920/1080', tagline: 'The Soul of Africa' },
    { name: 'Japan', flag: '🇯🇵', heroImage: 'https://picsum.photos/seed/japan-hero/1920/1080', tagline: 'Land of the Rising Sun' },
    { name: 'Peru', flag: '🇵🇪', heroImage: 'https://picsum.photos/seed/peru-hero/1920/1080', tagline: 'Empire of Hidden Treasures' },
    { name: 'Greece', flag: '🇬🇷', heroImage: 'https://picsum.photos/seed/greece-hero/1920/1080', tagline: 'The Cradle of Western Civilization' },
    { name: 'Canada', flag: '🇨🇦', heroImage: 'https://picsum.photos/seed/canada-hero/1920/1080', tagline: 'The Great White North' },
    { name: 'Australia', flag: '🇦🇺', heroImage: 'https://picsum.photos/seed/australia-hero/1920/1080', tagline: 'The Land Down Under' },
    { name: 'Italy', flag: '🇮🇹', heroImage: 'https://picsum.photos/seed/italy-hero/1920/1080', tagline: 'La Dolce Vita' },
    { name: 'Vietnam', flag: '🇻🇳', heroImage: 'https://picsum.photos/seed/vietnam-hero/1920/1080', tagline: 'The Timeless Charm of Southeast Asia' },
    { name: 'Argentina', flag: '🇦🇷', heroImage: 'https://picsum.photos/seed/argentina-hero/1920/1080', tagline: 'The Land of Silver' },
    { name: 'Egypt', flag: '🇪🇬', heroImage: 'https://picsum.photos/seed/egypt-hero/1920/1080', tagline: 'The Gift of the Nile' },
    { name: 'India', flag: '🇮🇳', heroImage: 'https://picsum.photos/seed/india-hero/1920/1080', tagline: 'Incredible India' },
    { name: 'UAE', flag: '🇦🇪', heroImage: 'https://picsum.photos/seed/uae-hero/1920/1080', tagline: 'The Land of Seven Emirates' },
    { name: 'Thailand', flag: '🇹🇭', heroImage: 'https://picsum.photos/seed/thailand-hero/1920/1080', tagline: 'The Land of Smiles' },
    { name: 'Cambodia', flag: '🇰🇭', heroImage: 'https://picsum.photos/seed/cambodia-hero/1920/1080', tagline: 'Kingdom of Wonder' },
    { name: 'Singapore', flag: '🇸🇬', heroImage: 'https://picsum.photos/seed/singapore-hero/1920/1080', tagline: 'The Lion City' },
    { name: 'Malaysia', flag: '🇲🇾', heroImage: 'https://picsum.photos/seed/malaysia-hero/1920/1080', tagline: 'Truly Asia' },
    { name: 'South Korea', flag: '🇰🇷', heroImage: 'https://picsum.photos/seed/korea-hero/1920/1080', tagline: 'The Land of the Morning Calm' },
    { name: 'France', flag: '🇫🇷', heroImage: 'https://picsum.photos/seed/france-hero/1920/1080', tagline: 'The City of Light' },
    { name: 'Spain', flag: '🇪🇸', heroImage: 'https://picsum.photos/seed/spain-hero/1920/1080', tagline: 'The Kingdom of the Sun' },
];

export const packagesData: Omit<Package, 'id' | 'image' | 'aiReasoning'>[] = [
  {
    title: 'Serengeti Wildlife Safari',
    destination: 'Serengeti National Park',
    country: 'Tanzania',
    continent: 'Africa',
    duration: '7',
    price: 3499,
    gallery: [
      'https://picsum.photos/seed/safari1/1200/800',
      'https://picsum.photos/seed/safari2/1200/800',
      'https://picsum.photos/seed/safari3/1200/800',
    ],
    rating: 4.9,
    reviewCount: 152,
    type: 'Safari',
    difficulty: 'Moderate',
    highlights: ['Big Five Sighting', 'Maasai Village Visit', 'Hot Air Balloon Safari'],
    description: 'Experience the raw beauty of the Serengeti, home to the Great Migration. Witness breathtaking landscapes and an abundance of wildlife in their natural habitat.',
    itinerary: [
      { day: 1, title: 'Arrival in Arusha', description: 'Transfer to your lodge and relax.' },
      { day: 2, title: 'Tarangire National Park', description: 'Full day game drive to see elephants and baobab trees.' },
      { day: 3, title: 'Central Serengeti', description: 'Explore the heart of the Serengeti, seeking out the Big Five.' },
      { day: 4, title: 'Ngorongoro Crater', description: 'Descend into the crater for a unique wildlife viewing experience.' },
      { day: 5, title: 'Departure', description: 'Return to Arusha for your flight home.' },
    ],
    inclusions: ['4x4 Vehicle', 'Park Fees', 'Experienced Guide', 'Full Board Accommodation'],
    exclusions: ['International Flights', 'Visa Fees', 'Gratuities'],
    availableDates: ['2025-07-15', '2025-08-01', '2025-09-10'],
  },
  {
    title: 'Kyoto Cultural Expedition',
    destination: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    duration: '5',
    price: 2899,
    gallery: [
      'https://picsum.photos/seed/kyoto1/1200/800',
      'https://picsum.photos/seed/kyoto2/1200/800',
      'https://picsum.photos/seed/kyoto3/1200/800',
    ],
    rating: 4.8,
    reviewCount: 210,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Kinkaku-ji Temple', 'Gion District Geisha Spotting', 'Arashiyama Bamboo Grove'],
    description: 'Immerse yourself in the ancient traditions and serene beauty of Kyoto. From golden temples to tranquil gardens, discover the heart of old Japan.',
    itinerary: [
        { day: 1, title: 'Arrival in Kyoto', description: 'Check into your traditional ryokan.' },
        { day: 2, title: 'Temples and Shrines', description: 'Visit Fushimi Inari and Kinkaku-ji.' },
        { day: 3, title: 'Gion and Tea Ceremony', description: 'Explore the historic Gion district and participate in a traditional tea ceremony.' },
        { day: 4, title: 'Arashiyama', description: 'Walk through the bamboo grove and visit the monkey park.' },
        { day: 5, title: 'Departure', description: 'Enjoy a final Japanese breakfast before heading to the airport.' },
    ],
    inclusions: ['Accommodation', 'Guided Tours', 'Tea Ceremony', 'Public Transport Pass'],
    exclusions: ['International Flights', 'Lunches and Dinners', 'Personal Expenses'],
    availableDates: ['2025-04-05', '2025-05-20', '2025-10-15'],
  },
  {
    title: 'Machu Picchu Inca Trail',
    destination: 'Cusco & Machu Picchu',
    country: 'Peru',
    continent: 'South America',
    duration: '8',
    price: 2950,
    gallery: [
      'https://picsum.photos/seed/peru1/1200/800',
      'https://picsum.photos/seed/peru2/1200/800',
      'https://picsum.photos/seed/peru3/1200/800',
    ],
    rating: 4.9,
    reviewCount: 340,
    type: 'Adventure',
    difficulty: 'Hard',
    highlights: ['Classic Inca Trail', 'Sunrise at Machu Picchu', 'Sacred Valley Tour'],
    description: 'Trek the ancient paths of the Incas to the lost city of Machu Picchu. A challenging but rewarding journey through stunning Andean landscapes.',
    itinerary: [
        { day: 1, title: 'Acclimatization in Cusco', description: 'Explore Cusco and the Sacred Valley.' },
        { day: 2, title: 'Inca Trail Trek', description: 'Four days of trekking through breathtaking scenery.' },
        { day: 3, title: 'Machu Picchu Tour', description: 'Guided tour of the ancient citadel.' },
        { day: 4, title: 'Departure', description: 'Return to Cusco for departure.' },
    ],
    inclusions: ['Inca Trail Permit', 'Porters and Cook', 'Camping Equipment', 'Machu Picchu Entrance'],
    exclusions: ['International Flights', 'Sleeping Bag', 'Travel Insurance'],
    availableDates: ['2025-06-10', '2025-07-22', '2025-08-18'],
  },
  {
    title: 'Greek Islands Hopping',
    destination: 'Santorini, Mykonos, Crete',
    country: 'Greece',
    continent: 'Europe',
    duration: '10',
    price: 4200,
    gallery: [
      'https://picsum.photos/seed/greece1/1200/800',
      'https://picsum.photos/seed/greece2/1200/800',
      'https://picsum.photos/seed/greece3/1200/800',
    ],
    rating: 4.7,
    reviewCount: 188,
    type: 'Beach',
    difficulty: 'Easy',
    highlights: ['Santorini Caldera Sunset', 'Mykonos Nightlife', 'Historical Knossos Palace'],
    description: 'Discover the magic of the Greek Islands. From the iconic white-washed villages of Santorini to the vibrant beaches of Mykonos, this is the ultimate Mediterranean escape.',
    itinerary: [
        { day: 1, title: 'Santorini', description: 'Explore Oia and Fira, and enjoy a catamaran cruise.' },
        { day: 2, title: 'Mykonos', description: 'Relax on the famous beaches and explore Mykonos Town.' },
        { day: 3, title: 'Crete', description: 'Visit Knossos Palace and hike the Samaria Gorge.' },
        { day: 4, title: 'Departure', description: 'Fly out from Heraklion.' },
    ],
    inclusions: ['Ferry Tickets', '4-star Hotels', 'Santorini Catamaran Cruise', 'Airport Transfers'],
    exclusions: ['International Flights', 'Most Meals', 'Optional Activities'],
    availableDates: ['2025-07-01', '2025-08-12', '2025-09-05'],
  },
  {
    title: 'Canadian Rockies Adventure',
    destination: 'Banff & Jasper',
    country: 'Canada',
    continent: 'North America',
    duration: '9',
    price: 3800,
    gallery: [
        'https://picsum.photos/seed/canada1/1200/800',
        'https://picsum.photos/seed/canada2/1200/800',
        'https://picsum.photos/seed/canada3/1200/800',
    ],
    rating: 4.9,
    reviewCount: 255,
    type: 'Adventure',
    difficulty: 'Moderate',
    highlights: ['Lake Louise & Moraine Lake', 'Icefields Parkway Drive', 'Jasper Wildlife'],
    description: 'Explore the pristine wilderness of the Canadian Rockies. Witness turquoise lakes, towering glaciers, and abundant wildlife in two of Canada\'s most famous national parks.',
    itinerary: [],
    inclusions: ['National Park Passes', 'Accommodation', 'Ice Explorer Ride'],
    exclusions: ['Flights', 'Most Meals', 'Car Rental'],
    availableDates: ['2025-07-20', '2025-08-10', '2025-09-01'],
  },
  {
    title: 'Australian Outback Odyssey',
    destination: 'Uluru & Kings Canyon',
    country: 'Australia',
    continent: 'Australia',
    duration: '4',
    price: 2100,
    gallery: [
        'https://picsum.photos/seed/oz1/1200/800',
        'https://picsum.photos/seed/oz2/1200/800',
        'https://picsum.photos/seed/oz3/1200/800',
    ],
    rating: 4.6,
    reviewCount: 130,
    type: 'Safari',
    difficulty: 'Moderate',
    highlights: ['Uluru Sunrise & Sunset', 'Kings Canyon Rim Walk', 'Aboriginal Cultural Tour'],
    description: 'Journey into the heart of the Australian Outback to discover the spiritual significance and rugged beauty of Uluru and Kings Canyon.',
    itinerary: [],
    inclusions: ['Guided Tours', 'Accommodation', 'Park Entrance Fees'],
    exclusions: ['Flights to Alice Springs', 'Meals', 'Optional Camel Ride'],
    availableDates: ['2025-05-15', '2025-09-20', '2025-10-25'],
  },
  {
    title: 'Flavors of Italy',
    destination: 'Rome, Florence, Tuscany',
    country: 'Italy',
    continent: 'Europe',
    duration: '10',
    price: 3900,
    gallery: [
        'https://picsum.photos/seed/italy1/1200/800',
        'https://picsum.photos/seed/italy2/1200/800',
        'https://picsum.photos/seed/italy3/1200/800',
    ],
    rating: 4.8,
    reviewCount: 312,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Colosseum Tour', 'Tuscan Wine Tasting', 'Florence Art Museums'],
    description: 'A gastronomic and cultural journey through Italy\'s most iconic cities and countryside. Taste, see, and experience the best of Italian life.',
    itinerary: [],
    inclusions: ['Train Tickets', 'Accommodation', 'Cooking Class', 'Wine Tasting'],
    exclusions: ['Flights', 'City Taxes', 'Lunches and Dinners'],
    availableDates: ['2025-05-10', '2025-09-15', '2025-10-05'],
  },
  {
    title: 'Vibrant Vietnam',
    destination: 'Hanoi, Ha Long Bay, Hoi An',
    country: 'Vietnam',
    continent: 'Asia',
    duration: '12',
    price: 2500,
    gallery: [
        'https://picsum.photos/seed/vietnam1/1200/800',
        'https://picsum.photos/seed/vietnam2/1200/800',
        'https://picsum.photos/seed/vietnam3/1200/800',
    ],
    rating: 4.7,
    reviewCount: 280,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Ha Long Bay Cruise', 'Hoi An Lanterns', 'Hanoi Street Food Tour'],
    description: 'Experience the rich history, stunning landscapes, and delicious cuisine of Vietnam. From bustling cities to serene bays, this tour has it all.',
    itinerary: [],
    inclusions: ['Internal Flights', 'Accommodation', 'Ha Long Bay Cruise', 'Guided Tours'],
    exclusions: ['International Flights', 'Visa Fees', 'Some Meals'],
    availableDates: ['2025-03-10', '2025-04-12', '2025-11-20'],
  },
  {
    title: 'Patagonia Hiking Explorer',
    destination: 'El Chaltén & Torres del Paine',
    country: 'Argentina',
    continent: 'South America',
    duration: '14',
    price: 5500,
    gallery: [
        'https://picsum.photos/seed/patagonia1/1200/800',
        'https://picsum.photos/seed/patagonia2/1200/800',
        'https://picsum.photos/seed/patagonia3/1200/800',
    ],
    rating: 5.0,
    reviewCount: 195,
    type: 'Adventure',
    difficulty: 'Hard',
    highlights: ['Fitz Roy Trek', 'Perito Moreno Glacier', 'Torres del Paine W-Trek'],
    description: 'A trekker\'s paradise. Conquer the most iconic trails in Patagonia, witnessing granite spires, massive glaciers, and windswept plains.',
    itinerary: [],
    inclusions: ['All Accommodation', 'Guided Hikes', 'Glacier Tour', 'Bus Transfers'],
    exclusions: ['Flights', 'National Park Entrance Fees', 'Most Meals'],
    availableDates: ['2025-11-15', '2025-12-05', '2026-01-20'],
  },
  {
    title: 'Egyptian Wonders',
    destination: 'Cairo, Luxor, Aswan',
    country: 'Egypt',
    continent: 'Africa',
    duration: '9',
    price: 2750,
    gallery: [
        'https://picsum.photos/seed/egypt1/1200/800',
        'https://picsum.photos/seed/egypt2/1200/800',
        'https://picsum.photos/seed/egypt3/1200/800',
    ],
    rating: 4.7,
    reviewCount: 410,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Pyramids of Giza', 'Nile River Cruise', 'Valley of the Kings'],
    description: 'Journey back in time to the land of pharaohs. Explore ancient temples, cruise the legendary Nile, and marvel at the last remaining wonder of the ancient world.',
    itinerary: [],
    inclusions: ['Nile Cruise (Full Board)', 'Domestic Flights', 'Egyptologist Guide'],
    exclusions: ['International Flights', 'Visa', 'Entrance Fees to some sites'],
    availableDates: ['2025-02-15', '2025-03-20', '2025-10-28'],
  },
  // New Packages Start Here
  {
    title: 'Golden Triangle of India',
    destination: 'Delhi, Agra, Jaipur',
    country: 'India',
    continent: 'Asia',
    duration: '8',
    price: 1999,
    gallery: [
        'https://picsum.photos/seed/india1/1200/800',
        'https://picsum.photos/seed/india2/1200/800',
        'https://picsum.photos/seed/india3/1200/800',
    ],
    rating: 4.8,
    reviewCount: 280,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Taj Mahal at Sunrise', 'Amber Fort in Jaipur', 'Old Delhi Rickshaw Ride'],
    description: 'Discover the rich history and vibrant culture of India\'s famous Golden Triangle. From majestic monuments to bustling bazaars, this journey is a feast for the senses.',
    itinerary: [],
    inclusions: ['Accommodation', 'Private vehicle with driver', 'Guided tours'],
    exclusions: ['International flights', 'Visa fees', 'Lunches and dinners'],
    availableDates: ['2025-10-20', '2025-11-15', '2026-02-10'],
  },
  {
    title: 'Desert Calm: 4 Days of Culture & Escape in Abu Dhabi',
    destination: 'Abu Dhabi',
    country: 'UAE',
    continent: 'Asia',
    duration: '4',
    price: 870,
    gallery: [
        'https://picsum.photos/seed/abudhabi1/1200/800',
        'https://picsum.photos/seed/abudhabi2/1200/800',
        'https://picsum.photos/seed/abudhabi3/1200/800',
    ],
    rating: 4.8,
    reviewCount: 175,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Desert Safari Adventure'],
    description: 'Where golden sands meet timeless stories. Experience the cultural treasures and serene desert landscapes of Abu Dhabi.',
    itinerary: [
      { day: 1, title: 'Arrival & Coastal Calm', description: 'Private pickup from Abu Dhabi International Airport and check-in at your hotel. Enjoy a relaxing evening.' },
      { day: 2, title: 'Spiritual Icons & Cultural Treasures', description: 'Guided visits to the Sheikh Zayed Grand Mosque, BAPS Hindu Mandir, and the Louvre Abu Dhabi.' },
      { day: 3, title: 'Desert Adventure & Arabian Night', description: 'Enjoy a free morning before an afternoon desert safari with dune bashing, camel rides, a BBQ dinner, and cultural show.' },
      { day: 4, title: 'Nature & Farewell', description: 'A guided kayaking tour in Jubail Mangrove Park, last-minute shopping, and a private transfer to the airport for your departure.' },
    ],
    inclusions: [
      '3 nights hotel accommodation (choice of 4★ or 5★)',
      'Daily breakfast',
      'Private airport transfers (arrival & departure)',
      'All scheduled transfers to activities',
      'Entry tickets to Sheikh Zayed Grand Mosque, BAPS Hindu Mandir, and Louvre Abu Dhabi',
      'Desert Safari with BBQ dinner',
      'Jubail Mangrove Park kayaking experience',
      'English-speaking guide for key cultural visits',
      '24/7 on-ground support',
    ],
    exclusions: [
      'Flights to/from Abu Dhabi',
      'Travel insurance',
      'Meals other than breakfast and desert safari dinner',
      'Optional activities',
      'Personal expenses',
      'Visa fees (if applicable)',
    ],
    availableDates: ['2025-11-10', '2025-12-05', '2026-01-20'],
  },
  {
    title: 'Thai Island Paradise',
    destination: 'Phuket & Koh Phi Phi',
    country: 'Thailand',
    continent: 'Asia',
    duration: '9',
    price: 2200,
    gallery: [
        'https://picsum.photos/seed/thailand1/1200/800',
        'https://picsum.photos/seed/thailand2/1200/800',
        'https://picsum.photos/seed/thailand3/1200/800',
    ],
    rating: 4.6,
    reviewCount: 410,
    type: 'Beach',
    difficulty: 'Easy',
    highlights: ['Maya Bay Visit', 'Phang Nga Bay Sea Canoeing', 'Vibrant nightlife in Patong'],
    description: 'Relax and explore the world-famous beaches and limestone karsts of Southern Thailand. A perfect blend of adventure and relaxation.',
    itinerary: [],
    inclusions: ['Beachfront resort accommodation', 'Ferry transfers', 'James Bond Island tour'],
    exclusions: ['International flights', 'Most meals', 'National park fees'],
    availableDates: ['2025-12-10', '2026-01-15', '2026-02-20'],
  },
  {
    title: 'Temples of Angkor',
    destination: 'Siem Reap',
    country: 'Cambodia',
    continent: 'Asia',
    duration: '4',
    price: 1500,
    gallery: [
        'https://picsum.photos/seed/cambodia1/1200/800',
        'https://picsum.photos/seed/cambodia2/1200/800',
        'https://picsum.photos/seed/cambodia3/1200/800',
    ],
    rating: 4.9,
    reviewCount: 250,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Angkor Wat at Sunrise', 'Bayon Temple\'s stone faces', 'Ta Prohm (the "Tomb Raider" temple)'],
    description: 'Explore the magnificent and mysterious temples of the ancient Khmer empire, a UNESCO World Heritage site that will leave you in awe.',
    itinerary: [],
    inclusions: ['Boutique hotel', 'Angkor Pass', 'Private Tuk-tuk guide'],
    exclusions: ['International flights', 'Visa fees', 'Lunches and dinners'],
    availableDates: ['2025-11-25', '2026-01-20', '2026-03-05'],
  },
   {
    title: 'Gardens of Singapore',
    destination: 'Singapore',
    country: 'Singapore',
    continent: 'Asia',
    duration: '5',
    price: 2300,
    gallery: [
        'https://picsum.photos/seed/singapore1/1200/800',
        'https://picsum.photos/seed/singapore2/1200/800',
        'https://picsum.photos/seed/singapore3/1200/800',
    ],
    rating: 4.7,
    reviewCount: 300,
    type: 'City Break',
    difficulty: 'Easy',
    highlights: ['Gardens by the Bay', 'Marina Bay Sands Skypark', 'Hawker Centre Food Tour'],
    description: 'Discover the "City in a Garden," where futuristic architecture meets lush green spaces and a vibrant culinary scene.',
    itinerary: [],
    inclusions: ['4-star hotel', 'Airport transfers', 'Gardens by the Bay admission'],
    exclusions: ['Flights', 'Most meals', 'Optional tours'],
    availableDates: ['2025-10-15', '2026-02-20', '2026-04-10'],
  },
  {
    title: 'Kuala Lumpur & Malacca',
    destination: 'Kuala Lumpur & Malacca',
    country: 'Malaysia',
    continent: 'Asia',
    duration: '6',
    price: 1800,
    gallery: [
        'https://picsum.photos/seed/malaysia1/1200/800',
        'https://picsum.photos/seed/malaysia2/1200/800',
        'https://picsum.photos/seed/malaysia3/1200/800',
    ],
    rating: 4.6,
    reviewCount: 220,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Petronas Twin Towers', 'Batu Caves', 'Historic Malacca River Cruise'],
    description: 'Experience the contrast of modern Kuala Lumpur and the rich history of UNESCO-listed Malacca.',
    itinerary: [],
    inclusions: ['Accommodation', 'Coach transfer to Malacca', 'KL Tower ticket'],
    exclusions: ['Flights', 'Lunches and dinners', 'Visa fees'],
    availableDates: ['2025-11-01', '2026-03-15', '2026-05-20'],
  },
  {
    title: 'Seoul K-Wave & Culture',
    destination: 'Seoul',
    country: 'South Korea',
    continent: 'Asia',
    duration: '7',
    price: 2600,
    gallery: [
        'https://picsum.photos/seed/seoul1/1200/800',
        'https://picsum.photos/seed/seoul2/1200/800',
        'https://picsum.photos/seed/seoul3/1200/800',
    ],
    rating: 4.8,
    reviewCount: 310,
    type: 'City Break',
    difficulty: 'Easy',
    highlights: ['Gyeongbok Palace', 'DMZ Tour', 'K-pop Dance Class', 'Myeongdong Shopping'],
    description: 'Dive into the dynamic energy of Seoul, from ancient palaces to the global phenomenon of K-pop and K-beauty.',
    itinerary: [],
    inclusions: ['Centrally located hotel', 'DMZ Tour', 'K-pop dance class', 'T-money transport card'],
    exclusions: ['Flights', 'Most meals', 'Personal shopping'],
    availableDates: ['2025-04-20', '2025-09-25', '2025-10-18'],
  },
  {
    title: 'Parisian Romance',
    destination: 'Paris',
    country: 'France',
    continent: 'Europe',
    duration: '5',
    price: 2800,
    gallery: [
        'https://picsum.photos/seed/paris1/1200/800',
        'https://picsum.photos/seed/paris2/1200/800',
        'https://picsum.photos/seed/paris3/1200/800',
    ],
    rating: 4.8,
    reviewCount: 350,
    type: 'City Break',
    difficulty: 'Easy',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Seine River Cruise'],
    description: 'Experience the art, history, and romance of the City of Lights. From iconic landmarks to charming streets, Paris is always a good idea.',
    itinerary: [],
    inclusions: ['4-star central hotel', 'Museum Pass', 'Seine River Cruise'],
    exclusions: ['Flights', 'Most meals', 'Metro tickets'],
    availableDates: ['2025-05-15', '2025-09-10', '2025-10-20'],
  },
  {
    title: 'Spanish Sunshine',
    destination: 'Barcelona & Madrid',
    country: 'Spain',
    continent: 'Europe',
    duration: '8',
    price: 3200,
    gallery: [
        'https://picsum.photos/seed/spain1/1200/800',
        'https://picsum.photos/seed/spain2/1200/800',
        'https://picsum.photos/seed/spain3/1200/800',
    ],
    rating: 4.7,
    reviewCount: 290,
    type: 'Cultural',
    difficulty: 'Easy',
    highlights: ['Sagrada Familia', 'Prado Museum', 'Tapas & Flamenco show'],
    description: 'Immerse yourself in the vibrant culture of Spain, from the architectural wonders of Barcelona to the royal history of Madrid.',
    itinerary: [],
    inclusions: ['High-speed train between cities', 'Accommodation', 'Flamenco Show with Dinner'],
    exclusions: ['Flights', 'Most meals', 'City taxes'],
    availableDates: ['2025-06-10', '2025-09-05', '2025-10-01'],
  },
];

export const reviews: Review[] = [
  { id: '1', packageId: 'serengeti-wildlife-safari', userName: 'Alice', rating: 5, comment: 'Absolutely breathtaking! Our guide was incredible. Saw the Big Five!', date: '2024-07-20T10:00:00Z', verified: true },
  { id: '2', packageId: 'serengeti-wildlife-safari', userName: 'Bob', rating: 5, comment: 'The hot air balloon ride was a highlight. A must-do.', date: '2024-07-18T14:30:00Z', verified: true },
  { id: '3', packageId: 'kyoto-cultural-expedition', userName: 'Charlie', rating: 5, comment: 'Kyoto is magical. The ryokan stay was so authentic.', date: '2024-06-10T09:00:00Z', verified: true },
  { id: '4', packageId: 'kyoto-cultural-expedition', userName: 'Diana', rating: 4, comment: 'Loved the tour, but wish there was more free time to explore on our own.', date: '2024-06-12T11:20:00Z', verified: true },
  { id: '5', packageId: 'machu-picchu-inca-trail', userName: 'Ethan', rating: 5, comment: 'Toughest thing I\'ve ever done, but worth every second. The views are unreal.', date: '2024-08-01T18:00:00Z', verified: true },
  { id: '6', packageId: 'machu-picchu-inca-trail', userName: 'Fiona', rating: 5, comment: 'Our porters were superheroes. The food they cooked on the trail was amazing.', date: '2024-08-02T12:00:00Z', verified: true },
  { id: '7', packageId: 'greek-islands-hopping', userName: 'George', rating: 4, comment: 'Santorini was as beautiful as the pictures. Mykonos was a bit too crowded for me.', date: '2024-07-25T16:45:00Z', verified: true },
  { id: '8', packageId: 'canadian-rockies-adventure', userName: 'Hannah', rating: 5, comment: 'I cried when I saw Lake Louise. The color of the water is something you have to see to believe.', date: '2024-08-15T13:00:00Z', verified: true },
  { id: '9', packageId: 'egyptian-wonders', userName: 'Ian', rating: 5, comment: 'The Nile cruise was so relaxing and our Egyptologist guide brought history to life. Incredible trip.', date: '2024-03-05T09:30:00Z', verified: false },
  { id: '10', packageId: 'patagonia-hiking-explorer', userName: 'Jane', rating: 5, comment: 'Mind-blowing landscapes. The W-Trek was challenging but so rewarding. Be prepared for all four seasons in one day!', date: '2024-02-10T20:00:00Z', verified: true },
  { id: '11', packageId: 'flavors-of-italy', userName: 'Kevin', rating: 5, comment: 'The cooking class in Tuscany was the highlight of our trip. Absolutely delicious food and wine.', date: '2024-05-30T19:00:00Z', verified: true },
  { id: '12', packageId: 'vibrant-vietnam', userName: 'Laura', rating: 4, comment: 'Ha Long Bay is stunning, but the boat was a bit dated. Hoi An was my favorite part.', date: '2024-04-20T11:00:00Z', verified: true },
  { id: '13', packageId: 'serengeti-wildlife-safari', userName: 'Mike', rating: 4, comment: 'Great wildlife sightings, but the accommodation was more basic than expected for the price.', date: '2024-07-22T08:00:00Z', verified: true },
  { id: '14', packageId: 'machu-picchu-inca-trail', userName: 'Nora', rating: 5, comment: 'The altitude is no joke, but the guides were fantastic at managing the pace. Reaching the Sun Gate at sunrise was a moment I\'ll never forget.', date: '2024-08-05T07:15:00Z', verified: true },
  { id: '15', packageId: 'kyoto-cultural-expedition', userName: 'Oscar', rating: 5, comment: 'Walking through the Arashiyama Bamboo Grove felt like being in another world. Japan is amazing.', date: '2024-06-14T15:00:00Z', verified: false },
  { id: '16', packageId: 'greek-islands-hopping', userName: 'Penny', rating: 5, comment: 'The perfect romantic getaway. The catamaran cruise in Santorini was magical.', date: '2024-07-28T21:00:00Z', verified: true },
  { id: '17', packageId: 'canadian-rockies-adventure', userName: 'Quinn', rating: 5, comment: 'The Icefields Parkway is the most beautiful drive I have ever been on. Saw a grizzly bear (from a safe distance!).', date: '2024-08-18T17:00:00Z', verified: true },
  { id: '18', packageId: 'australian-outback-odyssey', userName: 'Rachel', rating: 4, comment: 'Uluru is awe-inspiring, but be prepared for the flies! The cultural tour was very insightful.', date: '2024-10-01T06:00:00Z', verified: true },
  { id: '19', packageId: 'egyptian-wonders', userName: 'Sam', rating: 5, comment: 'Standing in front of the Pyramids is a surreal experience. I felt like I was in a movie.', date: '2024-03-10T10:45:00Z', verified: true },
  { id: '20', packageId: 'flavors-of-italy', userName: 'Tina', rating: 5, comment: 'I ate my weight in pasta and have no regrets. Rome was chaotic but wonderful.', date: '2024-06-02T13:20:00Z', verified: true },
  { id: '21', packageId: 'golden-triangle-of-india', userName: 'Umar', rating: 5, comment: 'The Taj Mahal is even more stunning in person. Our guide was incredibly knowledgeable.', date: '2024-11-01T08:00:00Z', verified: true },
  { id: '22', packageId: 'desert-calm-4-days-of-culture-escape-in-abu-dhabi', userName: 'Vera', rating: 5, comment: 'The desert safari was so much fun! The Grand Mosque is a must-see.', date: '2024-12-01T17:30:00Z', verified: true },
  { id: '23', packageId: 'parisian-romance', userName: 'Will', rating: 5, comment: 'Paris is everything I dreamed of. The river cruise at night was incredibly romantic.', date: '2024-09-20T21:00:00Z', verified: true },
];

export const continents: Continent[] = [
    { name: 'Africa', image: 'https://picsum.photos/seed/africa/800/600', dataAiHint: 'savannah animal' },
    { name: 'Asia', image: 'https://picsum.photos/seed/asia/800/600', dataAiHint: 'temple asia' },
    { name: 'Europe', image: 'https://picsum.photos/seed/europe/800/600', dataAiHint: 'old city' },
    { name: 'North America', image: 'https://picsum.photos/seed/northamerica/800/600', dataAiHint: 'mountain lake' },
    { name: 'South America', image: 'https://picsum.photos/seed/southamerica/800/600', dataAiHint: 'inca ruins' },
    { name: 'Australia', image: 'https://picsum.photos/seed/australia/800/600', dataAiHint: 'outback desert' },
    { name: 'Antarctica', image: 'https://picsum.photos/seed/antarctica/800/600', dataAiHint: 'iceberg penguin' },
];
