
import type { Package } from '@/types';

// This file contains the real, bookable packages for your live site.
export const realPackagesData: Omit<Package, 'id' | 'aiReasoning'>[] = [
    {
      title: 'Desert Calm: 4 Days of Culture & Escape in Abu Dhabi',
      destination: 'Abu Dhabi',
      country: 'UAE',
      continent: 'Asia',
      duration: '4',
      price: 649,
      image: 'https://picsum.photos/seed/camel-desert-ride/1200/800',
      gallery: ['https://picsum.photos/seed/camel-desert-ride/1200/800'],
      rating: 4.8,
      reviewCount: 175,
      // type: 'Cultural',
      theme: 'cultural',
      difficulty: 'Easy',
      highlights: ['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Desert Safari Adventure'],
      description: 'Where golden sands meet timeless stories. Experience the cultural treasures and serene desert landscapes of Abu Dhabi.',
      itinerary: [
        { day: 1, title: 'Arrival', description: 'Private pickup from Abu Dhabi International Airport (AUH) to the hotel.' },
        { day: 2, title: 'Spiritual Icons & Cultural Treasures', description: 'Morning pickup from the hotel for a guided visit to Sheikh Zayed Grand Mosque, followed by BAPS Hindu Mandir and Louvre Abu Dhabi. Return transfer to the hotel in the afternoon.' },
        { day: 3, title: 'Desert Adventure', description: 'Free morning. Afternoon pickup from the hotel for an Evening Desert  Safari with dune bashing and BBQ dinner. Late evening return transfer to the hotel. *Shared*' },
        { day: 4, title: 'Nature & Farewell', description: 'Morning pickup from the hotel for a kayaking tour at Jubail Mangrove Park. Following the activity, a final private transfer from the hotel to AUH for departure.' },
      ],
      inclusions: [
        '3 nights hotel accommodation (choice of 4★ or 5★)',
        'Daily breakfast',
        'Private airport transfers (arrival & departure)',
        'All scheduled transfers to activities',
        'Entry tickets to Sheikh Zayed Grand Mosque, BAPS Hindu Mandir, and Louvre Abu Dhabi',
        'Desert Safari with BBQ dinner',
        'Jubail Mangrove Park kayaking experience',
        'English-speaking guide for key cultural visits',
        '24/7 on-ground support',
      ],
      exclusions: [
        'Flights to/from Abu Dhabi',
        'Travel insurance',
        'Meals other than breakfast and desert safari dinner',
        'Optional activities',
        'Personal expenses',
        'Visa fees (if applicable)',
      ],
      availableDates: ['2025-11-10', '2025-12-05', '2026-01-20', '2026-02-15'],
      reviews: [],
    },
    {
      title: 'Abu Dhabi Essentials',
      destination: 'Abu Dhabi & Dubai',
      country: 'UAE',
      continent: 'Asia',
      duration: '4',
      price: 449,
      image: 'https://images.pexels.com/photos/3214995/pexels-photo-3214995.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      gallery: ['https://images.pexels.com/photos/3214995/pexels-photo-3214995.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
      rating: 4.9,
      reviewCount: 210,
      // type: 'Cultural',
      theme: 'city',
      difficulty: 'Moderate',
      highlights: ['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Burj Khalifa', 'Desert Safari'],
      description: 'Private pickups, cultural icons and a desert adventure with a 4★ hotel stay — perfect 4-day taste of Abu Dhabi and Dubai.',
      itinerary: [
        { day: 1, title: 'Arrival in Abu Dhabi', description: 'Private pickup from Abu Dhabi International Airport (AUH) to the hotel. Check-in and rest.' },
        { day: 2, title: 'Cultural Treasures', description: 'Pickup from hotel. Visit: Sheikh Zayed Grand Mosque, AUH city sightseeing, Louvre Museum, BAPS Temple. Afternoon return to hotel.' },
        { day: 3, title: 'Desert Adventure', description: 'Free morning. Afternoon pickup between 2:30–3:00 PM for shared Desert Safari with dune bashing, sandboarding & BBQ dinner. Late return to hotel.' },
        { day: 4, title: 'Departure', description: 'Checkout and return transfer to airport (if included) or continuation of trip.' },
      ],
      inclusions: [
        '3 nights hotel stay - 4★ category',
        'Daily breakfast',
        'Private airport pickup (AUH arrival)',
        'All scheduled transportation to attractions',
        'Desert Safari (shared) with dinner',
        'Tickets to: Sheikh Zayed Grand Mosque, BAPS Temple, Louvre Abu Dhabi',
        'English-speaking guide for cultural tours',
        '24/7 on-trip support'
      ],
      exclusions: [
        'Flights to/from UAE',
        'Lunches & dinners (except desert safari BBQ dinner)',
        'Personal expenses (souvenirs, tips, etc.)',
        'Optional activities not mentioned in the itinerary',
        'Visa fees and travel insurance'
      ],
      availableDates: ['2025-10-15', '2025-11-22', '2025-12-10', '2026-01-25', '2026-02-20'],
      reviews: [],
    },
    {
      title: 'Sands & Skylines: 7 Days Across Abu Dhabi & Dubai',
      destination: 'Abu Dhabi & Dubai',
      country: 'UAE',
      continent: 'Asia',
      duration: '7',
      price: 849,
      image: 'https://images.pexels.com/photos/3214995/pexels-photo-3214995.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      gallery: ['https://images.pexels.com/photos/3214995/pexels-photo-3214995.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
      rating: 4.9,
      reviewCount: 210,
      // type: 'Cultural',
      theme: 'city',
      difficulty: 'Easy',
      highlights: ['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Burj Khalifa', 'Desert Safari'],
      description: 'From sacred sands to shimmering towers, experience the best of the UAE in one epic journey.',
      itinerary: [
        { day: 1, title: 'Arrival & Coastal Welcome in Abu Dhabi', description: 'Private pickup from Abu Dhabi International Airport (AUH) and check-in at your hotel. Optional sunset stroll along the Corniche.' },
        { day: 2, title: 'Abu Dhabi: Culture, Art & Sacred Sites', description: 'Visit the Sheikh Zayed Grand Mosque and the BAPS Hindu Mandir, followed by an exploration of the Louvre Abu Dhabi.' },
        { day: 3, title: 'Abu Dhabi: Desert Adventure', description: 'Free morning for relaxation, followed by an evening Desert Safari with dune bashing, camel rides, and a BBQ dinner under the stars.' },
        { day: 4, title: 'Dubai Arrival & Marina Vibes', description: 'Private transfer to Dubai. Check-in to your hotel and explore the stunning Dubai Marina or JBR Walk in the evening.' },
        { day: 5, title: 'Icons of Dubai', description: 'Ascend the Burj Khalifa for breathtaking views, then explore the massive Dubai Mall and watch the spectacular Fountain Show.' },
        { day: 6, title: 'Dubai: Desert or Water Thrill (Choose Your Day)', description: 'Choose between another thrilling desert safari or a fun-filled day at Aquaventure Waterpark or IMG Worlds of Adventure.' },
        { day: 7, title: 'Dubai: Souks, Culture & Departure', description: 'Explore Old Dubai with a tour of Al Fahidi Historical District, an abra boat ride on the Creek, and a visit to the Gold & Spice Souks before your flight from DXB.' },
      ],
      inclusions: [
        '6 nights hotel stay (3 in Abu Dhabi, 3 in Dubai) - 4★ category',
        'Daily breakfast',
        'Private airport transfers (AUH arrival, DXB departure)',
        'Private intercity transfer from Abu Dhabi to Dubai',
        'All scheduled transportation to attractions',
        'Tickets to: Sheikh Zayed Grand Mosque, BAPS Hindu Temple, Louvre Abu Dhabi, Desert Safari (with dinner), Burj Khalifa At The Top',
        'Abra boat ride across Dubai Creek',
        'English-speaking guide for cultural tours',
        '24/7 on-trip support',
      ],
      exclusions: [
        'Flights to/from UAE',
        'Lunches & dinners (except desert safari)',
        'Personal expenses (souvenirs, tips, etc.)',
        'Optional activities not mentioned in the itinerary',
        'Visa fees and travel insurance',
      ],
      availableDates: ['2025-10-15', '2025-11-22', '2025-12-10', '2026-01-25', '2026-02-20'],
      reviews: [],
    },
  ];
