
import type { Package } from '@/types';

// This file contains the real, bookable packages for your live site.
export const realPackagesData: Omit<Package, 'id' | 'image' | 'aiReasoning'>[] = [
    {
      title: 'Desert Calm: 4 Days of Culture & Escape in Abu Dhabi',
      destination: 'Abu Dhabi',
      country: 'UAE',
      continent: 'Asia',
      duration: '4',
      price: 870,
      gallery: [
          'https://picsum.photos/seed/uae-grand-mosque/1200/800',
          'https://picsum.photos/seed/uae-louvre-museum/1200/800',
          'https://picsum.photos/seed/uae-desert-adventure/1200/800',
          'https://picsum.photos/seed/uae-mangrove-kayak/1200/800',
      ],
      rating: 4.8,
      reviewCount: 175,
      type: 'Cultural',
      theme: 'cultural',
      difficulty: 'Easy',
      highlights: ['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Desert Safari Adventure'],
      description: 'Where golden sands meet timeless stories. Experience the cultural treasures and serene desert landscapes of Abu Dhabi.',
      itinerary: [
        { day: 1, title: 'Arrival & Coastal Calm', description: 'Private pickup from Abu Dhabi International Airport and check-in at your hotel. Enjoy a relaxing evening.' },
        { day: 2, title: 'Spiritual Icons & Cultural Treasures', description: 'Guided visits to the Sheikh Zayed Grand Mosque, BAPS Hindu Mandir, and the Louvre Abu Dhabi.' },
        { day: 3, title: 'Desert Adventure & Arabian Night', description: 'Enjoy a free morning before an afternoon desert safari with dune bashing, camel rides, a BBQ dinner, and cultural show.' },
        { day: 4, title: 'Nature & Farewell', description: 'A guided kayaking tour in Jubail Mangrove Park, last-minute shopping, and a private transfer to the airport for your departure.' },
      ],
      inclusions: [
        '3 nights hotel accommodation (choice of 4★ or 5★)',
        'Daily breakfast',
        'Private airport transfers (arrival & departure)',
        'All scheduled transfers to activities',
        'Entry tickets to Sheikh Zayed Grand Mosque, BAPS Hindu Mandir, and Louvre Abu Dhabi',
        'Desert Safari with BBQ dinner',
        'Jubail Mangrove Park kayaking experience',
        'English-speaking guide for key cultural visits',
        '24/7 on-ground support',
      ],
      exclusions: [
        'Flights to/from Abu Dhabi',
        'Travel insurance',
        'Meals other than breakfast and desert safari dinner',
        'Optional activities',
        'Personal expenses',
        'Visa fees (if applicable)',
      ],
      availableDates: ['2025-11-10', '2025-12-05', '2026-01-20', '2026-02-15'],
      reviews: [],
    },
    {
      title: 'Sands & Skylines: 7 Days Across Abu Dhabi & Dubai',
      destination: 'Abu Dhabi & Dubai',
      country: 'UAE',
      continent: 'Asia',
      duration: '7',
      price: 1390,
      gallery: [
        'https://picsum.photos/seed/dubai-burj-khalifa/1200/800',
        'https://picsum.photos/seed/uae-grand-mosque-interior/1200/800',
        'https://picsum.photos/seed/dubai-marina-night/1200/800',
        'https://picsum.photos/seed/dubai-gold-souk/1200/800',
        'https://picsum.photos/seed/uae-desert-camel-ride/1200/800',
      ],
      rating: 4.9,
      reviewCount: 210,
      type: 'Cultural',
      theme: 'city',
      difficulty: 'Easy',
      highlights: ['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Burj Khalifa', 'Desert Safari'],
      description: 'From sacred sands to shimmering towers, experience the best of the UAE in one epic journey.',
      itinerary: [
        { day: 1, title: 'Arrival & Coastal Welcome in Abu Dhabi', description: 'Private pickup from Abu Dhabi International Airport (AUH) and check-in at your hotel. Optional sunset stroll along the Corniche.' },
        { day: 2, title: 'Abu Dhabi: Culture, Art & Sacred Sites', description: 'Visit the Sheikh Zayed Grand Mosque and the BAPS Hindu Mandir, followed by an exploration of the Louvre Abu Dhabi.' },
        { day: 3, title: 'Abu Dhabi: Desert Adventure', description: 'Free morning for relaxation, followed by an evening Desert Safari with dune bashing, camel rides, and a BBQ dinner under the stars.' },
        { day: 4, title: 'Dubai Arrival & Marina Vibes', description: 'Private transfer to Dubai. Check-in to your hotel and explore the stunning Dubai Marina or JBR Walk in the evening.' },
        { day: 5, title: 'Icons of Dubai', description: 'Ascend the Burj Khalifa for breathtaking views, then explore the massive Dubai Mall and watch the spectacular Fountain Show.' },
        { day: 6, title: 'Dubai: Desert or Water Thrill (Choose Your Day)', description: 'Choose between another thrilling desert safari or a fun-filled day at Aquaventure Waterpark or IMG Worlds of Adventure.' },
        { day: 7, title: 'Dubai: Souks, Culture & Departure', description: 'Explore Old Dubai with a tour of Al Fahidi Historical District, an abra boat ride on the Creek, and a visit to the Gold & Spice Souks before your flight from DXB.' },
      ],
      inclusions: [
        '6 nights hotel stay (3 in Abu Dhabi, 3 in Dubai) - 4★ category',
        'Daily breakfast',
        'Private airport transfers (AUH arrival, DXB departure)',
        'Private intercity transfer from Abu Dhabi to Dubai',
        'All scheduled transportation to attractions',
        'Tickets to: Sheikh Zayed Grand Mosque, BAPS Hindu Temple, Louvre Abu Dhabi, Desert Safari (with dinner), Burj Khalifa At The Top',
        'Abra boat ride across Dubai Creek',
        'English-speaking guide for cultural tours',
        '24/7 on-trip support',
      ],
      exclusions: [
        'Flights to/from UAE',
        'Lunches & dinners (except desert safari)',
        'Personal expenses (souvenirs, tips, etc.)',
        'Optional activities not mentioned in the itinerary',
        'Visa fees and travel insurance',
      ],
      availableDates: ['2025-10-15', '2025-11-22', '2025-12-10', '2026-01-25', '2026-02-20'],
      reviews: [],
    },
  ];
